### ISSUE TITLE
Open Graph (Share Images)

### ISSUE THREAD

**Issue by AngelCrawford** [AngelCrawford/blog#116]
Huge hat ein internes Open Graph Template dafür hier: https://gohugo.io/templates/embedded/#open-graph

https://cloudcannon.com/tutorials/hugo-seo-best-practices/#provide-for-social-tags-and-the-open-graph-protocol

Link teilen auf Plattformen, wie Whatsapp, FB oder Twitter (sollte schön aussehen, mit Bild).
**https://www.zachleat.com/web/automatic-opengraph/**
- [x] config.yaml SEO Daten überarbeitet?

```toml
[params.seo]
    twitterHandle = "crawford_ftw" #Twitter name, to bind shared cards to your profile
    # TODO: Keywords bestimmen
    keywords = "Webcard, Profil Karte, Angel Crawford"

# TODO: Soziale Medien einfügen
[[params.social]]
    name = "Facebook"
    link = "#"
    icon = "facebook-circle-line"
```

- [x] Featured Image als Bild zum Teilen der Seite benutzen! Dafür müssen die Templates von Hugo umgeschrieben werden
  * https://gohugo.io/templates/internal#open-graph
  * Hugo Templates: https://github.com/gohugoio/hugo/tree/master/tpl/tplimpl/embedded/templates
- [x] [Opengraph](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html) Feature Image benutzen, ansonsten das erste Bild aus dem Artikel
- [x] [Twitter Cards](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html) Feature Image benutzen, ansonsten das erste Bild aus dem Artikel
  - [ ] Da ich mit mehreren Autoren unter Umständen arbeite, sollte der SEO Kram in der config.toml nur als "else" stehen
  `if is single page, then load twitter from first author | else load twitter from config.yml`
  _
  ![image](https://user-images.githubusercontent.com/16148683/103448332-87ae0200-4c98-11eb-8679-ff24673bfd4b.png)
- [x] Feature Image sollte so aussehen
![2021-09-07 14_50_40-If I work really hard on my Open Graph Images, People will share my Blog Posts—z](https://user-images.githubusercontent.com/16148683/132347542-d9c2fbcd-1932-4c21-ac81-b74e83f659ae.png)
