### ISSUE TITLE
Image optimization

### ISSUE THREAD

**Issue by AngelCrawford** [AngelCrawford/blog#50]
## Todo
- [x] **Das umsetzen! https://laurakalbag.com/processing-responsive-images-with-hugo/**
## Bilder optimieren
- [x] `srcset` für alle Bilder auf dem Frontend hinzufügen => Nicht mehr nötig, da ich bereits alle Bilder per Hugo Image Processor anpasse
- [x] Alle Bilder richtig schneiden: https://gohugo.io/content-management/image-processing/
- [x] Bilder innerhalb eines Posts verbessern: https://discourse.gohugo.io/t/how-to-resize-downscale-images/14807/6
- [x] LazyLoad `<img loading="lazy" src="#" alt="Erst laden, wenn das Bild sichtbar wird">`

### srcset=""
* https://css-tricks.com/a-guide-to-the-responsive-images-syntax-in-html/
* https://css-tricks.com/fluid-images-in-a-variable-proportion-layout/
