### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by AngelCrawford** [AngelCrawford/blog#70]
## To-Do
- [ ] Tracking Code auf Webseite einrichten
  - [ ] Der Code sollte nur Environment Production tracken, **nicht** localhost
- [ ] Kontrollieren das wirklich kein Cookie gesetzt wird
- [ ] Schauen ob mit deaktiviertem JavaScript funktioniert
- [ ] Events ebenfalls tracken, siehe auch auf Profilecard
- [ ] Klick auf RSS Feed tracken

## Quellen
* [Umami](https://github.com/mikecao/umami)

**Comment by AngelCrawford** [comment]
Story 2.1 done (Umami)
